### ISSUE TITLE
Could this library be a replacement for RxJS?

### ISSUE THREAD

**Issue by dilame** [Effect-TS/stream#38]
I like RxJS, but it is not idiomatic to use `fp-ts`/`effect` together with RxJS. Is it possible to achieve same goals with `@effect/stream`?

**Comment by mikearnaldi** [comment]
Indeed it is possible to achieve similar goals, the two libraries are very different in the details though. Namely RxJS is based on observables and a push model, where a source pushes new events that downstream consumes. 

Streams are instead pull based, a consumer pulls the source for new elements, a push model can be achieved by using a queue and push to a queue letting streams take from the queue. 

This design decision is key in streams as it is the reason that Stream can be used with constant memory when processing large amounts of data

**Comment by IMax153** [comment]
Going to go ahead and close this issue given @mikearnaldi 's detailed answer.
